<?php
return [
    'MsgThriftIdentifyCodeService'=>array(
        'class'           => '\service\MsgCenter\MsgThriftIdentifyCodeServiceClient',
        'serverHost'        => '192.168.1.251',
        'serverPort'        => '50303',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'MsgThriftSmsService'=>array(
        'class'             => '\service\MsgCenter\MsgThriftSmsServiceClient',
        'serverHost'        => '192.168.1.251',
        'serverPort'        => '50302',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'MsgThriftEmailService'=>array(
        'class'             => '\service\MsgCenter\MsgThriftEmailServiceClient',
        'serverHost'        => '192.168.1.251',
        'serverPort'        => '50301',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'TOrderService'=>array(
        'class'             => '\service\order\TOrderServiceClient',
        'serverHost'        => '192.168.1.113',
        'serverPort'        => '51033',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'TPayService'=>array(
        'class'             => '\service\pay\TPayServiceClient',
        'serverHost'        => '192.168.1.113',
        'serverPort'        => '51044',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'TUserService'=>array(
        'class'             => '\service\user\TUserServiceClient',
        'serverHost'        => '192.168.1.113',
        'serverPort'        => '51055',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'TFundService'=>array(
        'class'             => '\service\fund\TFundServiceClient',
        'serverHost'        => '192.168.1.113',
        'serverPort'        => '51022',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'TCommonService'=>array(
        'class'             => '\service\common\TCommonServiceClient',
        'serverHost'        => '192.168.1.113',
        'serverPort'        => '51011',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
    'TActivityService'=>array(
        'class'             => '\service\activity\TActivityServiceClient',
        'serverHost'        => '192.168.1.113',
        'serverPort'        => '51066',
        'sendTimeout'       => 30,
        'recvTimeout'       => 30,
        'maxConnectTimes'   => 2,
    ),
];
